name: firstWorkflow

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  first_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: First Workflow Job Step
        run: echo "First Workflow Step1 executing"
