name: firstWorkflow

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      user_name:
        type: string
        required: true

jobs:
  first_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: First Workflow Job Step
        run: |
          echo "First Workflow Step1 executing"
          echo "User name is ${{ inputs.user_name}} "
