name: Main Workflow

on:
  workflow_dispatch:


jobs:
  call_first_workflow:
    name: Executing firstWorkflow
    uses: VishalRana2015/LearningWorkflows/.github/workflows/firstWorkflow.yml@main
    with:
      user_name: Vishal Rana

  call_second_workflow:
    name: Executing secondWorkflow
    needs: call_first_workflow
    uses: VishalRana2015/LearningWorkflows/.github/workflows/secondWorkflow.yml@main

  call_third_workflow:
    name: Executing thirdWorkflow
    needs: call_second_workflow
    uses: VishalRana2015/LearningWorkflows/.github/workflows/thirdWorkflow.yml@main
