on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: | 
          mkdir build
          echo "Build Output" > build/ouptut.txt 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/

      - name: Create Release and Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: build-artifact
          name: artifact_name
          tag: artifact_tag
