name: Second Workflow

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  second_workflow_only_job:
    runs-on: ubuntu-latest
    steps:
      - name: Second Workflow Job's Step 1
        run: echo "Second Workflow Job step1 executed"

  calls_third_workflow_job:
    name: Executing thirdWorkflow
    uses: VishalRana2015/LearningWorkflows/.github/workflows/thirdWorkflow.yml@main
